const fs = require('node:fs')
const path = require('node:path')
const test = require('node:test')
const assert = require('node:assert/strict')
const birthdays = require('../miniprogram/data/yuanhang-birthdays')
const data = require('../miniprogram/data/mock-data')
const { buildUpcomingBirthdayTasks } = require('../miniprogram/utils/birthday-reminders')

test('24 spreadsheet birthdays match yuanhang members one to one', () => {
  const yuanhangNames = new Set(data.members.filter(item => item.teamId === 'yuanhang').map(item => item.name))
  assert.equal(Object.keys(birthdays).length, 24)
  Object.keys(birthdays).forEach(name => assert.equal(yuanhangNames.has(name), true, `${name} must be in yuanhang roster`))
  assert.equal(data.members.find(item => item.name === '李珊珊').birthday, '07-22')
})

test('birthday todos appear automatically within 30 days', () => {
  const tasks = buildUpcomingBirthdayTasks(birthdays, new Date(2026, 6, 16))
  assert.deepEqual(tasks.map(item => [item.title, item.date]), [
    ['李珊珊生日关爱', '2026-07-22'],
    ['景殿贤生日关爱', '2026-08-06']
  ])
  tasks.forEach(item => {
    assert.equal(item.category, '生日关爱')
    assert.equal(item.autoGenerated, true)
  })
})

test('cloud API persists birthday todos before returning home and task data', () => {
  const cloud = fs.readFileSync(path.resolve(__dirname, '../cloudfunctions/api/index.js'), 'utf8')
  assert.match(cloud, /async function ensureBirthdayTodos\(\)/)
  assert.match(cloud, /系统根据成员生日提前30天自动生成/)
  assert.match(cloud, /sourceName === '李姗姗' \? '李珊珊'/)
  assert.match(cloud, /birthday: safeBirthday\(user\.birthday\) \|\|/)
  assert.match(cloud, /if \(viewer\) await ensureAutomaticTodos\(\)/)
  assert.match(cloud, /if \(!await todoViewer\(openid\)\)[\s\S]*await ensureAutomaticTodos\(\)/)
})
