const test = require('node:test')
const assert = require('node:assert/strict')

const cloudMonthlyMeeting = require('../cloudfunctions/api/monthly-meeting-todo')
const localMonthlyMeeting = require('../miniprogram/utils/monthly-meeting-todo')

const TARGET_CASES = [
  ['2026-07-31', { id: 'todo_yuanhang_monthly_meeting_2026_08', date: '2026-08-05', month: '2026-08', title: '远航八月例会+联谊' }],
  ['2026-08-05', { id: 'todo_yuanhang_monthly_meeting_2026_08', date: '2026-08-05', month: '2026-08', title: '远航八月例会+联谊' }],
  ['2026-08-06', { id: 'todo_yuanhang_monthly_meeting_2026_09', date: '2026-09-05', month: '2026-09', title: '远航九月例会+联谊' }],
  ['2026-12-06', { id: 'todo_yuanhang_monthly_meeting_2027_01', date: '2027-01-05', month: '2027-01', title: '远航一月例会+联谊' }]
]

test('cloud and local builders use the fifth day of the next non-past natural month', () => {
  TARGET_CASES.forEach(([referenceDate, expected]) => {
    assert.deepEqual(cloudMonthlyMeeting.buildMonthlyMeetingTarget(referenceDate), expected)
    assert.deepEqual(localMonthlyMeeting.buildMonthlyMeetingTarget(referenceDate), expected)
  })
})

test('legacy meeting matching is limited to the same Yuanhang date', () => {
  const target = cloudMonthlyMeeting.buildMonthlyMeetingTarget('2026-07-31')

  assert.equal(cloudMonthlyMeeting.matchesMonthlyMeetingTodo({
    organizationId: 'org_team_yuanhang',
    date: '2026-08-05',
    title: '远航第二次例会'
  }, target), true)
  assert.equal(cloudMonthlyMeeting.matchesMonthlyMeetingTodo({
    organizationId: 'org_team_yuanhang',
    date: '2026-08-05',
    title: '远航八月例会+联谊'
  }, target), true)
  assert.equal(cloudMonthlyMeeting.matchesMonthlyMeetingTodo({
    organizationId: 'org_team_jingying',
    date: '2026-08-05',
    title: '远航第二次例会'
  }, target), false)
  assert.equal(cloudMonthlyMeeting.matchesMonthlyMeetingTodo({
    organizationId: 'org_team_yuanhang',
    date: '2026-09-05',
    title: '远航第二次例会'
  }, target), false)
})

test('local fallback builds one visible Yuanhang meeting task', () => {
  const task = localMonthlyMeeting.buildUpcomingMonthlyMeetingTask(new Date(2026, 6, 31))

  assert.deepEqual(task, {
    _id: 'todo_yuanhang_monthly_meeting_2026_08',
    id: 'todo_yuanhang_monthly_meeting_2026_08',
    title: '远航八月例会+联谊',
    description: '系统根据自然月自动生成每月5日例会联谊提醒',
    category: '会议培训',
    date: '2026-08-05',
    month: '2026-08',
    day: '05',
    team: '远航服务队',
    teamId: 'yuanhang',
    organizationId: 'org_team_yuanhang',
    creatorId: 'system_monthly_meeting',
    status: 'pending',
    visible: true,
    visibleToAll: true,
    autoGenerated: true,
    monthlyMeeting: true
  })
})

function memoryTodoDependencies(initialTasks = []) {
  const tasks = initialTasks.map(item => ({ ...item }))
  const audits = []
  return {
    tasks,
    audits,
    dependencies: {
      todayText: () => '2026-07-31',
      timestamp: () => '2026-07-31T12:00:00.000Z',
      findTaskById: async id => tasks.find(item => item.id === id),
      findMatchingTasks: async target => tasks.filter(item => cloudMonthlyMeeting.matchesMonthlyMeetingTodo(item, target)),
      createTask: async data => { tasks.push({ ...data, _id: data.id }) },
      updateTask: async (task, data) => Object.assign(tasks.find(item => item._id === task._id), data),
      writeAudit: async (action, taskId, data) => { audits.push({ action, taskId, data }) }
    }
  }
}

test('cloud monthly meeting creation is idempotent and audited once', async () => {
  const memory = memoryTodoDependencies()

  const first = await cloudMonthlyMeeting.ensureMonthlyMeetingTodo(memory.dependencies)
  const second = await cloudMonthlyMeeting.ensureMonthlyMeetingTodo(memory.dependencies)

  assert.deepEqual(first, { action: 'create', taskId: 'todo_yuanhang_monthly_meeting_2026_08' })
  assert.deepEqual(second, { action: 'none', taskId: 'todo_yuanhang_monthly_meeting_2026_08' })
  assert.equal(memory.tasks.length, 1)
  assert.equal(memory.tasks[0].title, '远航八月例会+联谊')
  assert.equal(memory.tasks[0].date, '2026-08-05')
  assert.equal(memory.audits.length, 1)
  assert.equal(memory.audits[0].action, 'create')
})

test('cloud monthly meeting adopts the legacy row without overwriting manual fields', async () => {
  const memory = memoryTodoDependencies([{
    _id: 'legacy-document-id',
    id: 'legacy-business-id',
    organizationId: 'org_team_yuanhang',
    date: '2026-08-05',
    title: '远航第二次例会',
    status: 'completed',
    time: '18:30',
    location: '远航会议室',
    description: '人工填写的会议说明',
    visible: true
  }])

  const result = await cloudMonthlyMeeting.ensureMonthlyMeetingTodo(memory.dependencies)

  assert.deepEqual(result, { action: 'update', taskId: 'todo_yuanhang_monthly_meeting_2026_08' })
  assert.equal(memory.tasks.length, 1)
  assert.equal(memory.tasks[0].id, 'todo_yuanhang_monthly_meeting_2026_08')
  assert.equal(memory.tasks[0].title, '远航八月例会+联谊')
  assert.equal(memory.tasks[0].status, 'completed')
  assert.equal(memory.tasks[0].time, '18:30')
  assert.equal(memory.tasks[0].location, '远航会议室')
  assert.equal(memory.tasks[0].description, '人工填写的会议说明')
  assert.deepEqual(memory.audits.map(item => item.action), ['update'])
})

test('cloud monthly meeting uses deterministic and compatible targeted lookups instead of a capped task scan', async () => {
  const legacy = {
    _id: 'legacy-document-id',
    id: 'legacy-business-id',
    organizationId: 'org_team_yuanhang',
    date: '2026-08-05',
    title: '远航第二次例会',
    status: 'completed',
    time: '18:30',
    location: '远航会议室',
    description: '人工填写的会议说明',
    visible: true
  }
  const lookups = []
  let updated
  const result = await cloudMonthlyMeeting.ensureMonthlyMeetingTodo({
    todayText: () => '2026-07-31',
    timestamp: () => '2026-07-31T12:00:00.000Z',
    findTaskById: async id => {
      lookups.push({ type: 'id', id })
      return null
    },
    findMatchingTasks: async target => {
      lookups.push({ type: 'meeting', target })
      return [legacy]
    },
    createTask: async () => assert.fail('legacy task must be updated, not duplicated'),
    updateTask: async (task, data) => { updated = { task, data } },
    writeAudit: async () => {}
  })

  assert.deepEqual(result, { action: 'update', taskId: 'todo_yuanhang_monthly_meeting_2026_08' })
  assert.deepEqual(lookups, [
    { type: 'id', id: 'todo_yuanhang_monthly_meeting_2026_08' },
    { type: 'meeting', target: cloudMonthlyMeeting.buildMonthlyMeetingTarget('2026-07-31') }
  ])
  assert.equal(updated.data.status, undefined)
  assert.equal(updated.data.time, undefined)
  assert.equal(updated.data.location, undefined)
  assert.equal(updated.data.description, undefined)
})

test('monthly query adapter searches by organization plus deterministic id or compatible date and title', async () => {
  const { createMonthlyMeetingQueryAdapter } = require('../cloudfunctions/api/monthly-meeting-query')
  const queries = []
  const db = {
    command: { in: values => ({ values }) },
    collection() {
      return {
        where(where) {
          return {
            limit(limit) {
              return {
                get: async () => {
                  queries.push({ where, skip: 0, limit })
                  return { data: [{}] }
                }
              }
            },
            skip(skip) {
              return {
                limit(limit) {
                  return {
                    get: async () => {
                      queries.push({ where, skip, limit })
                      return { data: skip ? [] : [{}] }
                    }
                  }
                }
              }
            }
          }
        }
      }
    }
  }
  const adapter = createMonthlyMeetingQueryAdapter({
    db,
    collectionName: 'todo',
    organizationId: 'org_team_yuanhang',
    pageSize: 1
  })
  const target = cloudMonthlyMeeting.buildMonthlyMeetingTarget('2026-07-31')

  await adapter.findTaskById(target.id)
  await adapter.findMatchingTasks(target)

  assert.deepEqual(queries[0].where, {
    organizationId: 'org_team_yuanhang',
    id: target.id
  })
  assert.deepEqual(queries[1].where, {
    organizationId: 'org_team_yuanhang',
    date: target.date,
    title: { values: ['远航第二次例会', target.title] }
  })
})
